name: weave_app
description: A modern social Flutter app built using GetX and MVC architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management (Controllers)
  get: ^4.7.2

  # Responsive UI
  responsive_sizer: ^3.3.1

  # UI Components & Icons
  flutter_svg: ^2.2.1
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/fonts/
  # Fonts
  fonts:
    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
